# Generated by Django 2.1.8 on 2020-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_size', models.CharField(max_length=100)),
                ('pro_update_time', models.DateField()),
            ],
        ),
    ]
