# Generated by Django 2.1.8 on 2020-07-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_grad', models.IntegerField()),
                ('city_person_num', models.IntegerField()),
                ('city_proname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.ProInfo')),
            ],
        ),
    ]
